<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- Created with Inkscape (http://www.inkscape.org/) -->

<svg
   xmlns:dc="http://purl.org/dc/elements/1.1/"
   xmlns:cc="http://creativecommons.org/ns#"
   xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
   xmlns:svg="http://www.w3.org/2000/svg"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
   width="774.18481mm"
   height="409.96307mm"
   viewBox="0 0 2743.1745 1452.6251"
   id="svg2"
   version="1.1"
   inkscape:version="0.91 r13725"
   sodipodi:docname="dockerfile_layers.svg"
   inkscape:export-filename="/Users/bebatut/Documents/post_doc_freiburg/training/2016/docker_foundry_ws_12_16/images/dockerfile_layers.png"
   inkscape:export-xdpi="90"
   inkscape:export-ydpi="90">
  <defs
     id="defs4">
    <marker
       inkscape:isstock="true"
       style="overflow:visible"
       id="marker7498"
       refX="0"
       refY="0"
       orient="auto"
       inkscape:stockid="Arrow1Lend">
      <path
         transform="matrix(-0.8,0,0,-0.8,-10,0)"
         style="fill:#000000;fill-opacity:1;fill-rule:evenodd;stroke:#000000;stroke-width:1pt;stroke-opacity:1"
         d="M 0,0 5,-5 -12.5,0 5,5 0,0 Z"
         id="path7500"
         inkscape:connector-curvature="0" />
    </marker>
    <marker
       inkscape:stockid="Arrow1Lend"
       orient="auto"
       refY="0"
       refX="0"
       id="Arrow1Lend"
       style="overflow:visible"
       inkscape:isstock="true"
       inkscape:collect="always">
      <path
         id="path6794"
         d="M 0,0 5,-5 -12.5,0 5,5 0,0 Z"
         style="fill:#000000;fill-opacity:1;fill-rule:evenodd;stroke:#000000;stroke-width:1pt;stroke-opacity:1"
         transform="matrix(-0.8,0,0,-0.8,-10,0)"
         inkscape:connector-curvature="0" />
    </marker>
    <marker
       inkscape:stockid="Arrow1Mend"
       orient="auto"
       refY="0"
       refX="0"
       id="marker6365"
       style="overflow:visible"
       inkscape:isstock="true">
      <path
         id="path6367"
         d="M 0,0 5,-5 -12.5,0 5,5 0,0 Z"
         style="fill:#bafbff;fill-opacity:1;fill-rule:evenodd;stroke:#000000;stroke-width:1pt;stroke-opacity:1"
         transform="matrix(-0.4,0,0,-0.4,-4,0)"
         inkscape:connector-curvature="0" />
    </marker>
    <marker
       inkscape:isstock="true"
       style="overflow:visible"
       id="marker6313"
       refX="0"
       refY="0"
       orient="auto"
       inkscape:stockid="Arrow1Lstart">
      <path
         transform="matrix(0.8,0,0,0.8,10,0)"
         style="fill:#4dcbfe;fill-opacity:1;fill-rule:evenodd;stroke:#000000;stroke-width:1pt;stroke-opacity:1"
         d="M 0,0 5,-5 -12.5,0 5,5 0,0 Z"
         id="path6315"
         inkscape:connector-curvature="0" />
    </marker>
    <marker
       inkscape:isstock="true"
       style="overflow:visible"
       id="Arrow1Lstart"
       refX="0"
       refY="0"
       orient="auto"
       inkscape:stockid="Arrow1Lstart">
      <path
         transform="matrix(0.8,0,0,0.8,10,0)"
         style="fill:#4dcbfe;fill-opacity:1;fill-rule:evenodd;stroke:#000000;stroke-width:1pt;stroke-opacity:1"
         d="M 0,0 5,-5 -12.5,0 5,5 0,0 Z"
         id="path5215"
         inkscape:connector-curvature="0" />
    </marker>
    <marker
       inkscape:isstock="true"
       style="overflow:visible"
       id="Arrow1Mend-0"
       refX="0"
       refY="0"
       orient="auto"
       inkscape:stockid="Arrow1Mend">
      <path
         transform="matrix(-0.4,0,0,-0.4,-4,0)"
         style="fill:#000000;fill-opacity:1;fill-rule:evenodd;stroke:#000000;stroke-width:1pt;stroke-opacity:1"
         d="M 0,0 5,-5 -12.5,0 5,5 0,0 Z"
         id="path5224-3"
         inkscape:connector-curvature="0" />
    </marker>
    <marker
       inkscape:stockid="Arrow1Mend"
       orient="auto"
       refY="0"
       refX="0"
       id="marker6365-2"
       style="overflow:visible"
       inkscape:isstock="true">
      <path
         id="path6367-4"
         d="M 0,0 5,-5 -12.5,0 5,5 0,0 Z"
         style="fill:#979aec;fill-opacity:1;fill-rule:evenodd;stroke:#000000;stroke-width:1pt;stroke-opacity:1"
         transform="matrix(-0.4,0,0,-0.4,-4,0)"
         inkscape:connector-curvature="0" />
    </marker>
    <marker
       inkscape:stockid="Arrow1Mend"
       orient="auto"
       refY="0"
       refX="0"
       id="marker6365-21"
       style="overflow:visible"
       inkscape:isstock="true">
      <path
         id="path6367-6"
         d="M 0,0 5,-5 -12.5,0 5,5 0,0 Z"
         style="fill:#bafbff;fill-opacity:1;fill-rule:evenodd;stroke:#000000;stroke-width:1pt;stroke-opacity:1"
         transform="matrix(-0.4,0,0,-0.4,-4,0)"
         inkscape:connector-curvature="0" />
    </marker>
    <marker
       inkscape:stockid="Arrow1Mend"
       orient="auto"
       refY="0"
       refX="0"
       id="marker6365-2-6"
       style="overflow:visible"
       inkscape:isstock="true">
      <path
         id="path6367-4-2"
         d="M 0,0 5,-5 -12.5,0 5,5 0,0 Z"
         style="fill:#979aec;fill-opacity:1;fill-rule:evenodd;stroke:#000000;stroke-width:1pt;stroke-opacity:1"
         transform="matrix(-0.4,0,0,-0.4,-4,0)"
         inkscape:connector-curvature="0" />
    </marker>
    <marker
       inkscape:isstock="true"
       style="overflow:visible"
       id="Arrow1Mend-0-1"
       refX="0"
       refY="0"
       orient="auto"
       inkscape:stockid="Arrow1Mend">
      <path
         transform="matrix(-0.4,0,0,-0.4,-4,0)"
         style="fill:#000000;fill-opacity:1;fill-rule:evenodd;stroke:#000000;stroke-width:1pt;stroke-opacity:1"
         d="M 0,0 5,-5 -12.5,0 5,5 0,0 Z"
         id="path5224-3-3"
         inkscape:connector-curvature="0" />
    </marker>
    <marker
       inkscape:stockid="Arrow1Lend"
       orient="auto"
       refY="0"
       refX="0"
       id="Arrow1Lend-2"
       style="overflow:visible"
       inkscape:isstock="true">
      <path
         inkscape:connector-curvature="0"
         id="path6794-0"
         d="M 0,0 5,-5 -12.5,0 5,5 0,0 Z"
         style="fill:#000000;fill-opacity:1;fill-rule:evenodd;stroke:#000000;stroke-width:1pt;stroke-opacity:1"
         transform="matrix(-0.8,0,0,-0.8,-10,0)" />
    </marker>
    <marker
       inkscape:isstock="true"
       style="overflow:visible"
       id="marker7498-5"
       refX="0"
       refY="0"
       orient="auto"
       inkscape:stockid="Arrow1Lend">
      <path
         inkscape:connector-curvature="0"
         transform="matrix(-0.8,0,0,-0.8,-10,0)"
         style="fill:#000000;fill-opacity:1;fill-rule:evenodd;stroke:#000000;stroke-width:1pt;stroke-opacity:1"
         d="M 0,0 5,-5 -12.5,0 5,5 0,0 Z"
         id="path7500-9" />
    </marker>
    <marker
       inkscape:isstock="true"
       style="overflow:visible"
       id="marker7498-8"
       refX="0"
       refY="0"
       orient="auto"
       inkscape:stockid="Arrow1Lend">
      <path
         inkscape:connector-curvature="0"
         transform="matrix(-0.8,0,0,-0.8,-10,0)"
         style="fill:#000000;fill-opacity:1;fill-rule:evenodd;stroke:#000000;stroke-width:1pt;stroke-opacity:1"
         d="M 0,0 5,-5 -12.5,0 5,5 0,0 Z"
         id="path7500-7" />
    </marker>
    <marker
       inkscape:stockid="Arrow1Lend"
       orient="auto"
       refY="0"
       refX="0"
       id="Arrow1Lend-4"
       style="overflow:visible"
       inkscape:isstock="true"
       inkscape:collect="always">
      <path
         inkscape:connector-curvature="0"
         id="path6794-1"
         d="M 0,0 5,-5 -12.5,0 5,5 0,0 Z"
         style="fill:#000000;fill-opacity:1;fill-rule:evenodd;stroke:#000000;stroke-width:1pt;stroke-opacity:1"
         transform="matrix(-0.8,0,0,-0.8,-10,0)" />
    </marker>
  </defs>
  <sodipodi:namedview
     id="base"
     pagecolor="#ffffff"
     bordercolor="#666666"
     borderopacity="1.0"
     inkscape:pageopacity="0.0"
     inkscape:pageshadow="2"
     inkscape:zoom="0.175"
     inkscape:cx="1372.25"
     inkscape:cy="940.97349"
     inkscape:document-units="px"
     inkscape:current-layer="layer1"
     showgrid="false"
     inkscape:window-width="1280"
     inkscape:window-height="756"
     inkscape:window-x="13"
     inkscape:window-y="0"
     inkscape:window-maximized="0"
     fit-margin-top="0"
     fit-margin-left="0"
     fit-margin-right="0"
     fit-margin-bottom="0" />
  <metadata
     id="metadata7">
    <rdf:RDF>
      <cc:Work
         rdf:about="">
        <dc:format>image/svg+xml</dc:format>
        <dc:type
           rdf:resource="http://purl.org/dc/dcmitype/StillImage" />
        <dc:title></dc:title>
      </cc:Work>
    </rdf:RDF>
  </metadata>
  <g
     inkscape:label="Layer 1"
     inkscape:groupmode="layer"
     id="layer1"
     transform="translate(3224.3082,176.54604)">
    <path
       sodipodi:nodetypes="ccccccccc"
       inkscape:connector-curvature="0"
       id="path9355"
       d="m -2406.7621,-170.55616 -707.3172,0 c -90.7841,-5.90506 -109.1491,14.25232 -104.5839,93.574988 l 0,1122.900672 c 1.0506,67.4933 14.833,87.9676 104.5839,88.0705 l 946.7592,0 c 89.5118,2.9353 108.4927,-19.114 104.5839,-110.0882 l 0,-886.21074 z"
       style="fill:none;fill-rule:evenodd;stroke:#000000;stroke-width:10;stroke-linecap:butt;stroke-linejoin:miter;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1" />
    <path
       sodipodi:nodetypes="ccc"
       inkscape:connector-curvature="0"
       id="path9357"
       d="m -2404.0098,-173.30839 -2.7523,310.99945 344.0259,0"
       style="fill:none;fill-rule:evenodd;stroke:#000000;stroke-width:10;stroke-linecap:butt;stroke-linejoin:miter;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1" />
    <text
       xml:space="preserve"
       style="font-style:normal;font-weight:normal;font-size:70px;line-height:125%;font-family:sans-serif;letter-spacing:0px;word-spacing:0px;fill:#000000;fill-opacity:1;stroke:none;stroke-width:1px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1"
       x="-2884.2761"
       y="1269.3798"
       id="text4495"
       sodipodi:linespacing="125%"><tspan
         sodipodi:role="line"
         x="-2884.2761"
         y="1269.3798"
         id="tspan4497"><tspan
           x="-2884.2761"
           y="1269.3798"
           id="tspan4499">Dockerfile</tspan></tspan></text>
    <flowRoot
       xml:space="preserve"
       id="flowRoot6483"
       style="font-style:normal;font-weight:normal;font-size:40px;line-height:125%;font-family:sans-serif;letter-spacing:0px;word-spacing:0px;fill:#000000;fill-opacity:1;stroke:none;stroke-width:1px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1"><flowRegion
         id="flowRegion6485"><rect
           id="rect6487"
           width="717.20831"
           height="674.78192"
           x="-2773.8789"
           y="312.93054" /></flowRegion><flowPara
         id="flowPara6489" /></flowRoot>    <text
       xml:space="preserve"
       style="font-style:normal;font-weight:normal;font-size:35px;line-height:125%;font-family:sans-serif;letter-spacing:0px;word-spacing:0px;fill:#000000;fill-opacity:1;stroke:none;stroke-width:1px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1"
       x="-3156.5571"
       y="207.24756"
       id="text4325"
       sodipodi:linespacing="125%"><tspan
         sodipodi:role="line"
         x="-3156.5571"
         y="207.24756"
         id="tspan4327"><tspan
           x="-3156.5571"
           y="207.24756"
           id="tspan4329">FROM toolshed/requirements</tspan><tspan
           dx="0"
           x="-2646.8013"
           y="207.24756"
           id="tspan4331" /></tspan><tspan
         sodipodi:role="line"
         x="-3156.5571"
         y="250.99756"
         id="tspan4333"><tspan
           x="-3156.5571"
           y="250.99756"
           id="tspan4335" /></tspan><tspan
         sodipodi:role="line"
         x="-3156.5571"
         y="294.74756"
         id="tspan4337"><tspan
           x="-3156.5571"
           y="294.74756"
           id="tspan4339">MAINTAINER Björn A. Grüning, bjoern.gruening@gmail.com</tspan><tspan
           dx="0"
           x="-2122.0747"
           y="294.74756"
           id="tspan4341" /></tspan><tspan
         sodipodi:role="line"
         x="-3156.5571"
         y="338.49756"
         id="tspan4343"><tspan
           x="-3156.5571"
           y="338.49756"
           id="tspan4345" /></tspan><tspan
         sodipodi:role="line"
         x="-3156.5571"
         y="382.24756"
         id="tspan4347"><tspan
           x="-3156.5571"
           y="382.24756"
           id="tspan4349">ENV GALAXY_RELEASE=release_16.07...</tspan><tspan
           dx="0"
           x="-2450.6099"
           y="382.24756"
           id="tspan4351" /></tspan><tspan
         sodipodi:role="line"
         x="-3156.5571"
         y="425.99756"
         id="tspan4353"><tspan
           x="-3156.5571"
           y="425.99756"
           id="tspan4355" /></tspan><tspan
         sodipodi:role="line"
         x="-3156.5571"
         y="469.74756"
         id="tspan4357"><tspan
           x="-3156.5571"
           y="469.74756"
           id="tspan4359">RUN groupadd -r postgres -g $GALAXY_POSTGRES_GID \</tspan><tspan
           dx="0"
           x="-2170.1313"
           y="469.74756"
           id="tspan4361" /></tspan><tspan
         sodipodi:role="line"
         x="-3156.5571"
         y="513.49756"
         id="tspan4363"><tspan
           x="-3156.5571"
           y="513.49756"
           id="tspan4365">   ...</tspan><tspan
           dx="0"
           x="-3089.7017"
           y="513.49756"
           id="tspan4367" /></tspan><tspan
         sodipodi:role="line"
         x="-3156.5571"
         y="557.24756"
         id="tspan4369"><tspan
           x="-3156.5571"
           y="557.24756"
           id="tspan4371" /></tspan><tspan
         sodipodi:role="line"
         x="-3156.5571"
         y="600.99756"
         id="tspan4373"><tspan
           x="-3156.5571"
           y="600.99756"
           id="tspan4375">ADD ./bashrc $GALAXY_HOME/.bashrc</tspan><tspan
           dx="0"
           x="-2489.6431"
           y="600.99756"
           id="tspan4377" /></tspan><tspan
         sodipodi:role="line"
         x="-3156.5571"
         y="644.74756"
         id="tspan4379"><tspan
           x="-3156.5571"
           y="644.74756"
           id="tspan4381" /></tspan><tspan
         sodipodi:role="line"
         x="-3156.5571"
         y="688.49756"
         id="tspan4383"><tspan
           x="-3156.5571"
           y="688.49756"
           id="tspan4385">USER galaxy</tspan><tspan
           dx="0"
           x="-2934.6626"
           y="688.49756"
           id="tspan4387" /></tspan><tspan
         sodipodi:role="line"
         x="-3156.5571"
         y="732.24756"
         id="tspan4389"><tspan
           x="-3156.5571"
           y="732.24756"
           id="tspan4391" /></tspan><tspan
         sodipodi:role="line"
         x="-3156.5571"
         y="775.99756"
         id="tspan4393"><tspan
           x="-3156.5571"
           y="775.99756"
           id="tspan4395">WORKDIR $GALAXY_ROOT</tspan><tspan
           dx="0"
           x="-2693.0122"
           y="775.99756"
           id="tspan4397" /></tspan><tspan
         sodipodi:role="line"
         x="-3156.5571"
         y="819.74756"
         id="tspan4399"><tspan
           x="-3156.5571"
           y="819.74756"
           id="tspan4401" /></tspan><tspan
         sodipodi:role="line"
         x="-3156.5571"
         y="863.49756"
         id="tspan4403"><tspan
           x="-3156.5571"
           y="863.49756"
           id="tspan4405">EXPOSE :80</tspan><tspan
           dx="0"
           x="-2949.9067"
           y="863.49756"
           id="tspan4407" /></tspan><tspan
         sodipodi:role="line"
         x="-3156.5571"
         y="907.24756"
         id="tspan4409"><tspan
           x="-3156.5571"
           y="907.24756"
           id="tspan4411" /></tspan><tspan
         sodipodi:role="line"
         x="-3156.5571"
         y="950.99756"
         id="tspan4413"><tspan
           x="-3156.5571"
           y="950.99756"
           id="tspan4415">VOLUME [&quot;/export/&quot;, &quot;/data/&quot;, &quot;/var/lib/docker&quot;]</tspan><tspan
           dx="0"
           x="-2339.3208"
           y="950.99756"
           id="tspan4417" /></tspan><tspan
         sodipodi:role="line"
         x="-3156.5571"
         y="994.74756"
         id="tspan4419"><tspan
           x="-3156.5571"
           y="994.74756"
           id="tspan4421" /></tspan><tspan
         sodipodi:role="line"
         x="-3156.5571"
         y="1038.4976"
         id="tspan4423"><tspan
           x="-3156.5571"
           y="1038.4976"
           id="tspan4425">CMD [&quot;/usr/bin/startup&quot;]</tspan><tspan
           dx="0"
           x="-2733.8228"
           y="1038.4976"
           id="tspan4427" /></tspan><tspan
         sodipodi:role="line"
         x="-3156.5571"
         y="1082.2476"
         id="tspan4429"><tspan
           x="-3156.5571"
           y="1082.2476"
           id="tspan4431" /></tspan><tspan
         sodipodi:role="line"
         x="-3156.5571"
         y="1125.9976"
         id="tspan4433"><tspan
           x="-3156.5571"
           y="1125.9976"
           id="tspan4435" /></tspan><tspan
         sodipodi:role="line"
         x="-3156.5571"
         y="1169.7476"
         id="tspan4437"><tspan
           x="-3156.5571"
           y="1169.7476"
           id="tspan4439" /></tspan><tspan
         sodipodi:role="line"
         x="-3156.5571"
         y="1213.4976"
         id="tspan4441"><tspan
           x="-3156.5571"
           y="1213.4976"
           id="tspan4443" /></tspan><tspan
         sodipodi:role="line"
         x="-3156.5571"
         y="1257.2476"
         id="tspan4445"><tspan
           x="-3156.5571"
           y="1257.2476"
           id="tspan4447" /></tspan><tspan
         sodipodi:role="line"
         x="-3156.5571"
         y="1300.9976"
         id="tspan4449"><tspan
           x="-3156.5571"
           y="1300.9976"
           id="tspan4451" /></tspan><tspan
         sodipodi:role="line"
         x="-3156.5571"
         y="1344.7476"
         id="tspan4453"><tspan
           x="-3156.5571"
           y="1344.7476"
           id="tspan4455" /></tspan><tspan
         sodipodi:role="line"
         x="-3156.5571"
         y="1388.4976"
         id="tspan4457"><tspan
           x="-3156.5571"
           y="1388.4976"
           id="tspan4459" /></tspan><tspan
         sodipodi:role="line"
         x="-3156.5571"
         y="1432.2476"
         id="tspan4461"><tspan
           x="-3156.5571"
           y="1432.2476"
           id="tspan4463" /></tspan><tspan
         sodipodi:role="line"
         x="-3156.5571"
         y="1475.9976"
         id="tspan4465"><tspan
           x="-3156.5571"
           y="1475.9976"
           id="tspan4467" /></tspan><tspan
         sodipodi:role="line"
         x="-3156.5571"
         y="1519.7476"
         id="tspan4469"><tspan
           x="-3156.5571"
           y="1519.7476"
           id="tspan4471" /></tspan><tspan
         sodipodi:role="line"
         x="-3156.5571"
         y="1519.7476"
         id="tspan4473"><tspan
           x="-3156.5571"
           y="1563.4976"
           id="tspan4475" /></tspan></text>
    <text
       xml:space="preserve"
       style="font-style:normal;font-weight:normal;font-size:70px;line-height:125%;font-family:sans-serif;letter-spacing:0px;word-spacing:0px;fill:#000000;fill-opacity:1;stroke:none;stroke-width:1px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1"
       x="-1413.751"
       y="1261.5184"
       id="text4489"
       sodipodi:linespacing="125%"><tspan
         sodipodi:role="line"
         x="-1413.751"
         y="1261.5184"
         id="tspan4491"><tspan
           x="-1413.751"
           y="1261.5184"
           id="tspan4493">Layers</tspan></tspan></text>
    <rect
       style="fill:#aad3d2;fill-opacity:1;stroke:#000000;stroke-width:3;stroke-linecap:butt;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1"
       id="rect4793"
       width="1121.6521"
       height="137.14288"
       x="-1604.2858"
       y="1000.603"
       rx="0"
       ry="0" />
    <text
       xml:space="preserve"
       style="font-style:normal;font-weight:normal;font-size:70px;line-height:125%;font-family:sans-serif;letter-spacing:0px;word-spacing:0px;fill:#000000;fill-opacity:1;stroke:none;stroke-width:1px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1"
       x="-1557.1423"
       y="1097.5177"
       id="text4483"
       sodipodi:linespacing="125%"><tspan
         sodipodi:role="line"
         x="-1557.1423"
         y="1097.5177"
         id="tspan4485"><tspan
           x="-1557.1423"
           y="1097.5177"
           id="tspan4487">Kernel</tspan></tspan></text>
    <rect
       style="fill:#01ade6;fill-opacity:1;stroke:#000000;stroke-width:3;stroke-linecap:butt;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1"
       id="rect4793-0"
       width="908.13647"
       height="137.14282"
       x="-1604.2856"
       y="863.46008"
       rx="0"
       ry="0" />
    <text
       xml:space="preserve"
       style="font-style:normal;font-weight:normal;font-size:70px;line-height:125%;font-family:sans-serif;letter-spacing:0px;word-spacing:0px;fill:#000000;fill-opacity:1;stroke:none;stroke-width:1px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1"
       x="-1556.7679"
       y="951.34302"
       id="text4477"
       sodipodi:linespacing="125%"><tspan
         sodipodi:role="line"
         x="-1556.7679"
         y="951.34302"
         id="tspan4479"><tspan
           x="-1556.7679"
           y="951.34302"
           id="tspan4481">toolshed/requirements</tspan></tspan></text>
    <rect
       style="fill:#01ade6;fill-opacity:1;stroke:#000000;stroke-width:3;stroke-linecap:butt;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1"
       id="rect4793-0-3"
       width="908.40125"
       height="113.92664"
       x="-1604.2856"
       y="753.47601"
       rx="0"
       ry="0" />
    <rect
       style="fill:#01ade6;fill-opacity:1;stroke:#000000;stroke-width:3;stroke-linecap:butt;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1"
       id="rect4793-0-3-3"
       width="908.40125"
       height="113.92664"
       x="-1604.2856"
       y="526.51599"
       rx="0"
       ry="0" />
    <rect
       style="fill:#01ade6;fill-opacity:1;stroke:#000000;stroke-width:3;stroke-linecap:butt;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1"
       id="rect4793-0-3-5"
       width="908.40125"
       height="113.92664"
       x="-1604.2856"
       y="639.35175"
       rx="0"
       ry="0" />
    <rect
       style="fill:#01ade6;fill-opacity:1;stroke:#000000;stroke-width:3;stroke-linecap:butt;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1"
       id="rect4793-0-3-4"
       width="908.40125"
       height="113.92664"
       x="-1604.2856"
       y="411.90012"
       rx="0"
       ry="0" />
    <rect
       style="fill:#01ade6;fill-opacity:1;stroke:#000000;stroke-width:3;stroke-linecap:butt;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1"
       id="rect4793-0-3-53"
       width="908.40125"
       height="113.92664"
       x="-1604.2856"
       y="297.67401"
       rx="0"
       ry="0" />
    <rect
       style="fill:#01ade6;fill-opacity:1;stroke:#000000;stroke-width:3;stroke-linecap:butt;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1"
       id="rect4793-0-3-2"
       width="908.40125"
       height="113.92664"
       x="-1604.2856"
       y="184.04131"
       rx="0"
       ry="0" />
    <path
       style="fill:none;fill-rule:evenodd;stroke:#000000;stroke-width:3;stroke-linecap:butt;stroke-linejoin:miter;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1;marker-end:url(#Arrow1Lend)"
       d="m -2602.153,195.75285 670.5383,5.71429 310.1465,743.75942"
       id="path6749"
       inkscape:connector-curvature="0"
       sodipodi:nodetypes="ccc" />
    <rect
       style="fill:#01ade6;fill-opacity:1;stroke:#000000;stroke-width:3;stroke-linecap:butt;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1"
       id="rect4793-0-3-2-8"
       width="908.40125"
       height="113.92664"
       x="-1604.2856"
       y="70.007225"
       rx="0"
       ry="0" />
    <rect
       style="fill:#01ade6;fill-opacity:1;stroke:#000000;stroke-width:3;stroke-linecap:butt;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1"
       id="rect4793-0-3-2-5"
       width="908.40125"
       height="113.92664"
       x="-1604.2856"
       y="-42.760303"
       rx="0"
       ry="0" />
    <rect
       style="fill:#01ade6;fill-opacity:1;stroke:#000000;stroke-width:3;stroke-linecap:butt;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1"
       id="rect4793-0-3-2-4"
       width="908.40125"
       height="113.92664"
       x="-1604.2856"
       y="-154.7991"
       rx="0"
       ry="0" />
    <path
       style="fill:none;fill-rule:evenodd;stroke:#000000;stroke-width:3;stroke-linecap:butt;stroke-linejoin:miter;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1;marker-end:url(#marker7498-5)"
       d="m -2466.8944,592.07819 843.5216,-5.71429"
       id="path7476-2"
       inkscape:connector-curvature="0"
       sodipodi:nodetypes="cc" />
    <path
       style="fill:none;fill-rule:evenodd;stroke:#000000;stroke-width:3;stroke-linecap:butt;stroke-linejoin:miter;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1;marker-end:url(#Arrow1Lend-4)"
       d="m -2692.9071,1025.9744 833.3954,2.8571 221.5752,-1126.616557"
       id="path6749-0"
       inkscape:connector-curvature="0"
       sodipodi:nodetypes="ccc" />
  </g>
</svg>
