<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- Created with Inkscape (http://www.inkscape.org/) -->

<svg
   xmlns:dc="http://purl.org/dc/elements/1.1/"
   xmlns:cc="http://creativecommons.org/ns#"
   xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
   xmlns:svg="http://www.w3.org/2000/svg"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
   width="210mm"
   height="297mm"
   viewBox="0 0 744.09448819 1052.3622047"
   id="svg2"
   version="1.1"
   inkscape:version="0.91 r13725"
   sodipodi:docname="dockerfile_layers.svg"
   inkscape:export-filename="/Users/bebatut/Documents/post_doc_freiburg/training/2016/docker_foundry_ws_12_16/images/dockerfile_layers.png"
   inkscape:export-xdpi="90"
   inkscape:export-ydpi="90">
  <defs
     id="defs4">
    <marker
       inkscape:isstock="true"
       style="overflow:visible;"
       id="marker7498"
       refX="0.0"
       refY="0.0"
       orient="auto"
       inkscape:stockid="Arrow1Lend">
      <path
         transform="scale(0.8) rotate(180) translate(12.5,0)"
         style="fill-rule:evenodd;stroke:#000000;stroke-width:1pt;stroke-opacity:1;fill:#000000;fill-opacity:1"
         d="M 0.0,0.0 L 5.0,-5.0 L -12.5,0.0 L 5.0,5.0 L 0.0,0.0 z "
         id="path7500" />
    </marker>
    <marker
       inkscape:stockid="Arrow1Lend"
       orient="auto"
       refY="0.0"
       refX="0.0"
       id="Arrow1Lend"
       style="overflow:visible;"
       inkscape:isstock="true"
       inkscape:collect="always">
      <path
         id="path6794"
         d="M 0.0,0.0 L 5.0,-5.0 L -12.5,0.0 L 5.0,5.0 L 0.0,0.0 z "
         style="fill-rule:evenodd;stroke:#000000;stroke-width:1pt;stroke-opacity:1;fill:#000000;fill-opacity:1"
         transform="scale(0.8) rotate(180) translate(12.5,0)" />
    </marker>
    <marker
       inkscape:stockid="Arrow1Mend"
       orient="auto"
       refY="0.0"
       refX="0.0"
       id="marker6365"
       style="overflow:visible;"
       inkscape:isstock="true">
      <path
         id="path6367"
         d="M 0.0,0.0 L 5.0,-5.0 L -12.5,0.0 L 5.0,5.0 L 0.0,0.0 z "
         style="fill-rule:evenodd;stroke:#000000;stroke-width:1pt;stroke-opacity:1;fill:#bafbff;fill-opacity:1"
         transform="scale(0.4) rotate(180) translate(10,0)" />
    </marker>
    <marker
       inkscape:isstock="true"
       style="overflow:visible"
       id="marker6313"
       refX="0.0"
       refY="0.0"
       orient="auto"
       inkscape:stockid="Arrow1Lstart">
      <path
         transform="scale(0.8) translate(12.5,0)"
         style="fill-rule:evenodd;stroke:#000000;stroke-width:1pt;stroke-opacity:1;fill:#4dcbfe;fill-opacity:1"
         d="M 0.0,0.0 L 5.0,-5.0 L -12.5,0.0 L 5.0,5.0 L 0.0,0.0 z "
         id="path6315" />
    </marker>
    <marker
       inkscape:isstock="true"
       style="overflow:visible"
       id="Arrow1Lstart"
       refX="0.0"
       refY="0.0"
       orient="auto"
       inkscape:stockid="Arrow1Lstart">
      <path
         transform="scale(0.8) translate(12.5,0)"
         style="fill-rule:evenodd;stroke:#000000;stroke-width:1pt;stroke-opacity:1;fill:#4dcbfe;fill-opacity:1"
         d="M 0.0,0.0 L 5.0,-5.0 L -12.5,0.0 L 5.0,5.0 L 0.0,0.0 z "
         id="path5215" />
    </marker>
    <marker
       inkscape:isstock="true"
       style="overflow:visible"
       id="Arrow1Mend-0"
       refX="0"
       refY="0"
       orient="auto"
       inkscape:stockid="Arrow1Mend">
      <path
         transform="matrix(-0.4,0,0,-0.4,-4,0)"
         style="fill:#000000;fill-opacity:1;fill-rule:evenodd;stroke:#000000;stroke-width:1pt;stroke-opacity:1"
         d="M 0,0 5,-5 -12.5,0 5,5 0,0 Z"
         id="path5224-3"
         inkscape:connector-curvature="0" />
    </marker>
    <marker
       inkscape:stockid="Arrow1Mend"
       orient="auto"
       refY="0"
       refX="0"
       id="marker6365-2"
       style="overflow:visible"
       inkscape:isstock="true">
      <path
         id="path6367-4"
         d="M 0,0 5,-5 -12.5,0 5,5 0,0 Z"
         style="fill:#979aec;fill-opacity:1;fill-rule:evenodd;stroke:#000000;stroke-width:1pt;stroke-opacity:1"
         transform="matrix(-0.4,0,0,-0.4,-4,0)"
         inkscape:connector-curvature="0" />
    </marker>
    <marker
       inkscape:stockid="Arrow1Mend"
       orient="auto"
       refY="0"
       refX="0"
       id="marker6365-21"
       style="overflow:visible"
       inkscape:isstock="true">
      <path
         id="path6367-6"
         d="M 0,0 5,-5 -12.5,0 5,5 0,0 Z"
         style="fill:#bafbff;fill-opacity:1;fill-rule:evenodd;stroke:#000000;stroke-width:1pt;stroke-opacity:1"
         transform="matrix(-0.4,0,0,-0.4,-4,0)"
         inkscape:connector-curvature="0" />
    </marker>
    <marker
       inkscape:stockid="Arrow1Mend"
       orient="auto"
       refY="0"
       refX="0"
       id="marker6365-2-6"
       style="overflow:visible"
       inkscape:isstock="true">
      <path
         id="path6367-4-2"
         d="M 0,0 5,-5 -12.5,0 5,5 0,0 Z"
         style="fill:#979aec;fill-opacity:1;fill-rule:evenodd;stroke:#000000;stroke-width:1pt;stroke-opacity:1"
         transform="matrix(-0.4,0,0,-0.4,-4,0)"
         inkscape:connector-curvature="0" />
    </marker>
    <marker
       inkscape:isstock="true"
       style="overflow:visible"
       id="Arrow1Mend-0-1"
       refX="0"
       refY="0"
       orient="auto"
       inkscape:stockid="Arrow1Mend">
      <path
         transform="matrix(-0.4,0,0,-0.4,-4,0)"
         style="fill:#000000;fill-opacity:1;fill-rule:evenodd;stroke:#000000;stroke-width:1pt;stroke-opacity:1"
         d="M 0,0 5,-5 -12.5,0 5,5 0,0 Z"
         id="path5224-3-3"
         inkscape:connector-curvature="0" />
    </marker>
    <marker
       inkscape:stockid="Arrow1Lend"
       orient="auto"
       refY="0"
       refX="0"
       id="Arrow1Lend-2"
       style="overflow:visible"
       inkscape:isstock="true">
      <path
         inkscape:connector-curvature="0"
         id="path6794-0"
         d="M 0,0 5,-5 -12.5,0 5,5 0,0 Z"
         style="fill:#000000;fill-opacity:1;fill-rule:evenodd;stroke:#000000;stroke-width:1pt;stroke-opacity:1"
         transform="matrix(-0.8,0,0,-0.8,-10,0)" />
    </marker>
    <marker
       inkscape:isstock="true"
       style="overflow:visible"
       id="marker7498-5"
       refX="0"
       refY="0"
       orient="auto"
       inkscape:stockid="Arrow1Lend">
      <path
         inkscape:connector-curvature="0"
         transform="matrix(-0.8,0,0,-0.8,-10,0)"
         style="fill:#000000;fill-opacity:1;fill-rule:evenodd;stroke:#000000;stroke-width:1pt;stroke-opacity:1"
         d="M 0,0 5,-5 -12.5,0 5,5 0,0 Z"
         id="path7500-9" />
    </marker>
    <marker
       inkscape:isstock="true"
       style="overflow:visible"
       id="marker7498-8"
       refX="0"
       refY="0"
       orient="auto"
       inkscape:stockid="Arrow1Lend">
      <path
         inkscape:connector-curvature="0"
         transform="matrix(-0.8,0,0,-0.8,-10,0)"
         style="fill:#000000;fill-opacity:1;fill-rule:evenodd;stroke:#000000;stroke-width:1pt;stroke-opacity:1"
         d="M 0,0 5,-5 -12.5,0 5,5 0,0 Z"
         id="path7500-7" />
    </marker>
    <marker
       inkscape:stockid="Arrow1Lend"
       orient="auto"
       refY="0"
       refX="0"
       id="Arrow1Lend-4"
       style="overflow:visible"
       inkscape:isstock="true"
       inkscape:collect="always">
      <path
         inkscape:connector-curvature="0"
         id="path6794-1"
         d="M 0,0 5,-5 -12.5,0 5,5 0,0 Z"
         style="fill:#000000;fill-opacity:1;fill-rule:evenodd;stroke:#000000;stroke-width:1pt;stroke-opacity:1"
         transform="matrix(-0.8,0,0,-0.8,-10,0)" />
    </marker>
  </defs>
  <sodipodi:namedview
     id="base"
     pagecolor="#ffffff"
     bordercolor="#666666"
     borderopacity="1.0"
     inkscape:pageopacity="0.0"
     inkscape:pageshadow="2"
     inkscape:zoom="0.35"
     inkscape:cx="-1396.3439"
     inkscape:cy="717.25672"
     inkscape:document-units="px"
     inkscape:current-layer="layer1"
     showgrid="false"
     inkscape:window-width="1917"
     inkscape:window-height="1178"
     inkscape:window-x="1280"
     inkscape:window-y="1"
     inkscape:window-maximized="0" />
  <metadata
     id="metadata7">
    <rdf:RDF>
      <cc:Work
         rdf:about="">
        <dc:format>image/svg+xml</dc:format>
        <dc:type
           rdf:resource="http://purl.org/dc/dcmitype/StillImage" />
        <dc:title></dc:title>
      </cc:Work>
    </rdf:RDF>
  </metadata>
  <g
     inkscape:label="Layer 1"
     inkscape:groupmode="layer"
     id="layer1">
    <path
       sodipodi:nodetypes="ccccccccc"
       inkscape:connector-curvature="0"
       id="path9355"
       d="m -2406.7621,-170.55616 -707.3172,0 c -90.7841,-5.90506 -109.1491,14.25232 -104.5839,93.574988 l 0,1122.900672 c 1.0506,67.4933 14.833,87.9676 104.5839,88.0705 l 946.7592,0 c 89.5118,2.9353 108.4927,-19.114 104.5839,-110.0882 l 0,-886.21074 z"
       style="fill:none;fill-rule:evenodd;stroke:#000000;stroke-width:10;stroke-linecap:butt;stroke-linejoin:miter;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1" />
    <path
       sodipodi:nodetypes="ccc"
       inkscape:connector-curvature="0"
       id="path9357"
       d="m -2404.0098,-173.30839 -2.7523,310.99945 344.0259,0"
       style="fill:none;fill-rule:evenodd;stroke:#000000;stroke-width:10;stroke-linecap:butt;stroke-linejoin:miter;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1" />
    <flowRoot
       transform="matrix(5.8038317,0,0,5.8038317,-3253.6242,10.728616)"
       style="font-style:normal;font-weight:normal;font-size:12.06099796px;line-height:125%;font-family:sans-serif;letter-spacing:0px;word-spacing:0px;fill:#000000;fill-opacity:1;stroke:none;stroke-width:1px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1"
       id="flowRoot5497-8-7-4"
       xml:space="preserve"><flowRegion
         id="flowRegion5499-1-7-9"><rect
           style="font-size:12.06099796px"
           y="204.84422"
           x="63.63961"
           height="123.23861"
           width="273.75134"
           id="rect5501-4-7-6" /></flowRegion><flowPara
         id="flowPara5503-5-1-4">Dockerfile</flowPara></flowRoot>    <flowRoot
       xml:space="preserve"
       id="flowRoot6483"
       style="fill:black;stroke:none;stroke-opacity:1;stroke-width:1px;stroke-linejoin:miter;stroke-linecap:butt;fill-opacity:1;font-family:sans-serif;font-style:normal;font-weight:normal;font-size:40px;line-height:125%;letter-spacing:0px;word-spacing:0px"><flowRegion
         id="flowRegion6485"><rect
           id="rect6487"
           width="717.20831"
           height="674.78192"
           x="-2773.8789"
           y="312.93054" /></flowRegion><flowPara
         id="flowPara6489"></flowPara></flowRoot>    <flowRoot
       xml:space="preserve"
       id="flowRoot6510"
       style="font-style:normal;font-weight:normal;font-size:35px;line-height:125%;font-family:sans-serif;letter-spacing:0px;word-spacing:0px;fill:#000000;fill-opacity:1;stroke:none;stroke-width:1px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1"
       transform="translate(-390.84226,-180)"><flowRegion
         id="flowRegion6512"><rect
           id="rect6514"
           width="1574.2856"
           height="1385.7141"
           x="-2765.7144"
           y="352.36221"
           style="font-size:35px" /></flowRegion><flowPara
         id="flowPara6516">FROM toolshed/requirements</flowPara><flowPara
         id="flowPara6518" /><flowPara
         id="flowPara6596">MAINTAINER Björn A. Grüning, bjoern.gruening@gmail.com</flowPara><flowPara
         id="flowPara6526" /><flowPara
         id="flowPara6598">ENV GALAXY_RELEASE=release_16.07...</flowPara><flowPara
         id="flowPara6534" /><flowPara
         id="flowPara6540">RUN groupadd -r postgres -g $GALAXY_POSTGRES_GID \</flowPara><flowPara
         id="flowPara6592">   ...</flowPara><flowPara
         id="flowPara6600" /><flowPara
         id="flowPara6602">ADD ./bashrc $GALAXY_HOME/.bashrc</flowPara><flowPara
         id="flowPara6606" /><flowPara
         id="flowPara6608">USER galaxy</flowPara><flowPara
         id="flowPara6616" /><flowPara
         id="flowPara6618">WORKDIR $GALAXY_ROOT</flowPara><flowPara
         id="flowPara6620" /><flowPara
         id="flowPara6628">EXPOSE :80</flowPara><flowPara
         id="flowPara6639" /><flowPara
         id="flowPara6641">VOLUME [&quot;/export/&quot;, &quot;/data/&quot;, &quot;/var/lib/docker&quot;]</flowPara><flowPara
         id="flowPara6643" /><flowPara
         id="flowPara6645">CMD [&quot;/usr/bin/startup&quot;]</flowPara><flowPara
         id="flowPara6610" /><flowPara
         id="flowPara6612" /><flowPara
         id="flowPara6594"> </flowPara><flowPara
         id="flowPara6590" /><flowPara
         id="flowPara6542" /><flowPara
         id="flowPara6544" /><flowPara
         id="flowPara6546" /><flowPara
         id="flowPara6548" /><flowPara
         id="flowPara6550" /><flowPara
         id="flowPara6552" /><flowPara
         id="flowPara6554" /><flowPara
         id="flowPara6556" /><flowPara
         id="flowPara6558" /><flowPara
         id="flowPara6560" /><flowPara
         id="flowPara6562" /><flowPara
         id="flowPara6564" /><flowPara
         id="flowPara6566" /><flowPara
         id="flowPara6568" /><flowPara
         id="flowPara6570" /><flowPara
         id="flowPara6572" /><flowPara
         id="flowPara6574" /></flowRoot>    <flowRoot
       transform="matrix(5.8038317,0,0,5.8038317,-1783.0991,2.8672876)"
       style="font-style:normal;font-weight:normal;font-size:12.06099796px;line-height:125%;font-family:sans-serif;letter-spacing:0px;word-spacing:0px;fill:#000000;fill-opacity:1;stroke:none;stroke-width:1px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1"
       id="flowRoot5497-8-7-4-9"
       xml:space="preserve"><flowRegion
         id="flowRegion5499-1-7-9-6"><rect
           style="font-size:12.06099796px"
           y="204.84422"
           x="63.63961"
           height="123.23861"
           width="273.75134"
           id="rect5501-4-7-6-8" /></flowRegion><flowPara
         id="flowPara5503-5-1-4-4">Layers</flowPara></flowRoot>    <rect
       style="fill:#aad3d2;fill-opacity:1;stroke:#000000;stroke-width:3;stroke-linecap:butt;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1"
       id="rect4793"
       width="1121.6521"
       height="137.14288"
       x="-1604.2858"
       y="1000.603"
       rx="0"
       ry="0" />
    <flowRoot
       xml:space="preserve"
       id="flowRoot4795"
       style="font-style:normal;font-weight:normal;font-size:70px;line-height:125%;font-family:sans-serif;letter-spacing:0px;word-spacing:0px;fill:#000000;fill-opacity:1;stroke:none;stroke-width:1px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1"
       transform="translate(17.142857,32.526459)"><flowRegion
         id="flowRegion4797"><rect
           id="rect4799"
           width="621.42859"
           height="105.71429"
           x="-1574.2858"
           y="995.21936"
           style="font-size:70px" /></flowRegion><flowPara
         id="flowPara4801">Kernel</flowPara></flowRoot>    <rect
       style="fill:#01ade6;fill-opacity:1;stroke:#000000;stroke-width:3;stroke-linecap:butt;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1"
       id="rect4793-0"
       width="908.13647"
       height="137.14282"
       x="-1604.2856"
       y="863.46008"
       rx="0"
       ry="0" />
    <flowRoot
       xml:space="preserve"
       id="flowRoot4795-1"
       style="font-style:normal;font-weight:normal;font-size:70px;line-height:125%;font-family:sans-serif;letter-spacing:0px;word-spacing:0px;fill:#000000;fill-opacity:1;stroke:none;stroke-width:1px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1"
       transform="translate(17.517221,-113.64818)"><flowRegion
         id="flowRegion4797-9"><rect
           id="rect4799-4"
           width="896.19012"
           height="109.75488"
           x="-1574.2858"
           y="995.21936"
           style="font-size:70px" /></flowRegion><flowPara
         id="flowPara4801-1">toolshed/requirements</flowPara></flowRoot>    <rect
       style="fill:#01ade6;fill-opacity:1;stroke:#000000;stroke-width:3;stroke-linecap:butt;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1"
       id="rect4793-0-3"
       width="908.40125"
       height="113.92664"
       x="-1604.2856"
       y="753.47601"
       rx="0"
       ry="0" />
    <rect
       style="fill:#01ade6;fill-opacity:1;stroke:#000000;stroke-width:3;stroke-linecap:butt;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1"
       id="rect4793-0-3-3"
       width="908.40125"
       height="113.92664"
       x="-1604.2856"
       y="526.51599"
       rx="0"
       ry="0" />
    <rect
       style="fill:#01ade6;fill-opacity:1;stroke:#000000;stroke-width:3;stroke-linecap:butt;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1"
       id="rect4793-0-3-5"
       width="908.40125"
       height="113.92664"
       x="-1604.2856"
       y="639.35175"
       rx="0"
       ry="0" />
    <rect
       style="fill:#01ade6;fill-opacity:1;stroke:#000000;stroke-width:3;stroke-linecap:butt;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1"
       id="rect4793-0-3-4"
       width="908.40125"
       height="113.92664"
       x="-1604.2856"
       y="411.90012"
       rx="0"
       ry="0" />
    <rect
       style="fill:#01ade6;fill-opacity:1;stroke:#000000;stroke-width:3;stroke-linecap:butt;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1"
       id="rect4793-0-3-53"
       width="908.40125"
       height="113.92664"
       x="-1604.2856"
       y="297.67401"
       rx="0"
       ry="0" />
    <rect
       style="fill:#01ade6;fill-opacity:1;stroke:#000000;stroke-width:3;stroke-linecap:butt;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1"
       id="rect4793-0-3-2"
       width="908.40125"
       height="113.92664"
       x="-1604.2856"
       y="184.04131"
       rx="0"
       ry="0" />
    <path
       style="fill:none;fill-rule:evenodd;stroke:#000000;stroke-width:3;stroke-linecap:butt;stroke-linejoin:miter;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1;marker-end:url(#Arrow1Lend)"
       d="m -2602.153,195.75285 670.5383,5.71429 310.1465,743.75942"
       id="path6749"
       inkscape:connector-curvature="0"
       sodipodi:nodetypes="ccc" />
    <rect
       style="fill:#01ade6;fill-opacity:1;stroke:#000000;stroke-width:3;stroke-linecap:butt;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1"
       id="rect4793-0-3-2-8"
       width="908.40125"
       height="113.92664"
       x="-1604.2856"
       y="70.007225"
       rx="0"
       ry="0" />
    <rect
       style="fill:#01ade6;fill-opacity:1;stroke:#000000;stroke-width:3;stroke-linecap:butt;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1"
       id="rect4793-0-3-2-5"
       width="908.40125"
       height="113.92664"
       x="-1604.2856"
       y="-42.760303"
       rx="0"
       ry="0" />
    <rect
       style="fill:#01ade6;fill-opacity:1;stroke:#000000;stroke-width:3;stroke-linecap:butt;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1"
       id="rect4793-0-3-2-4"
       width="908.40125"
       height="113.92664"
       x="-1604.2856"
       y="-154.7991"
       rx="0"
       ry="0" />
    <path
       style="fill:none;fill-rule:evenodd;stroke:#000000;stroke-width:3;stroke-linecap:butt;stroke-linejoin:miter;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1;marker-end:url(#marker7498-5)"
       d="m -2466.8944,592.07819 843.5216,-5.71429"
       id="path7476-2"
       inkscape:connector-curvature="0"
       sodipodi:nodetypes="cc" />
    <path
       style="fill:none;fill-rule:evenodd;stroke:#000000;stroke-width:3;stroke-linecap:butt;stroke-linejoin:miter;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1;marker-end:url(#Arrow1Lend-4)"
       d="m -2692.9071,1025.9744 833.3954,2.8571 221.5752,-1126.616557"
       id="path6749-0"
       inkscape:connector-curvature="0"
       sodipodi:nodetypes="ccc" />
  </g>
</svg>
