- name: galaxyproject.galaxy
  version: 0.9.6
- name: galaxyproject.nginx
  version: 0.6.4
- name: galaxyproject.postgresql
  version: 1.0.2
- name: natefoo.postgresql_objects
  version: 1.1
- name: geerlingguy.pip
  version: 1.3.0
- src: uchida.miniconda
  version: 0.3.0
- src: usegalaxy_eu.galaxy_systemd
  version: 0.1.2
- src: usegalaxy_eu.certbot
  version: 0.1.3
