# Register workflows for Dockstore (https://dockstore.org/)
version: 1.2
workflows:
  - name: intro-short
    subclass: GALAXY
    publish: true
    primaryDescriptorPath: topics/introduction/tutorials/galaxy-intro-short/workflows/Galaxy-Workflow-galaxy-intro-short.ga
  - name: intro-everyone
    subclass: GALAXY
    publish: true
    primaryDescriptorPath: topics/introduction/tutorials/galaxy-intro-101-everyone/workflows/main_workflow.ga
  - name: de-novo
    subclass: GALAXY
    publish: true
    primaryDescriptorPath: topics/transcriptomics/tutorials/full-de-novo/workflows/main_workflow.ga
  - name: dip
    subclass: GALAXY
    publish: true
    primaryDescriptorPath: topics/variant-analysis/tutorials/dip/workflows/diploid.ga
  - name: genome-annotation
    subclass: GALAXY
    publish: true
    primaryDescriptorPath: topics/genome-annotation/tutorials/annotation-with-prokka/workflows/Galaxy-Workflow-Workflow_constructed_from_history__prokka-workflow_.ga
