source "https://rubygems.org"
gem "nokogiri", ">= 1.10.4"
gem 'addressable'
gem 'jekyll', '< 4'
gem 'jekyll-feed'
gem 'jekyll-environment-variables'
gem 'jekyll-github-metadata'
gem 'jekyll-scholar', '< 6'
gem 'jekyll-redirect-from'
gem 'jekyll-last-modified-at'
gem 'csl-styles'
gem 'awesome_bot'
gem 'html-proofer'
gem 'pkg-config'
gem 'kwalify'
