# frozen_string_literal: true
source "https://rubygems.org"
gem 'nokogiri'
gem 'addressable'
gem 'jekyll'
gem 'jekyll-feed'
gem 'jekyll-environment-variables'
gem 'jekyll-github-metadata'
gem 'jekyll-scholar'
gem 'csl-styles'
gem 'awesome_bot'
gem 'html-proofer'
gem 'pkg-config'
# gem 'addressable', '2.5.2'
# gem 'nokogiri', '1.10.0'
