cp ~/git/BMMB554/hugo/static/img/ref_vs_assembly.jpg ./
cp ~/git/BMMB554/hugo/static/img/mt_lib.png ./
cp ~/git/BMMB554/hugo/static/img/mt_qc.png ./
cp ~/git/BMMB554/hugo/static/img/mt_qc_plot.png ./
cp ~/git/BMMB554/hugo/static/img/mt_bwa_mem.png ./
cp ~/git/BMMB554/hugo/static/img/ * By using the middle button again mt_middle_button.png we select datasets 1 and 3 as **Select the first set of reads** and datasets 2 and 4 as **Select the second set of reads**. Galaxy will automatically launch two bwa-mem jobs using datasets 1,2 and 3,4 generating two resulting BAM files. ./
cp ~/git/BMMB554/hugo/static/img/mt_bam_merging.png ./
cp ~/git/BMMB554/hugo/static/img/mt_dedup.png ./
cp ~/git/BMMB554/hugo/static/img/mt_left_align.png ./
cp ~/git/BMMB554/hugo/static/img/mt_filtering.png ./
cp ~/git/BMMB554/hugo/static/img/mt_freebayes_genome.png ./
cp ~/git/BMMB554/hugo/static/img/mt_freebayes_regions.png ./
cp ~/git/BMMB554/hugo/static/img/mt_freebayes_alloptions.png ./
cp ~/git/BMMB554/hugo/static/img/mt_freebayes_popmodel.png ./
cp ~/git/BMMB554/hugo/static/img/mt_freebayes_allelic_scope.png ./
cp ~/git/BMMB554/hugo/static/img/mt_freebayes_inputfilters.png ./
cp ~/git/BMMB554/hugo/static/img/mt_biases.png ./
cp ~/git/BMMB554/hugo/static/img/mt_vcffilter.png ./
cp ~/git/BMMB554/hugo/static/img/mt_vcf_dataset_collapsed.png ./
cp ~/git/BMMB554/hugo/static/img/mt_vcf_dataset_expanded.png ./
cp ~/git/BMMB554/hugo/static/img/mt_vcfiobio.png ./
cp ~/git/BMMB554/hugo/static/img/mt_vcf_dataset_expanded.png ./
cp ~/git/BMMB554/hugo/static/img/mt_igv.png ./
cp ~/git/BMMB554/hugo/static/img/mt_vcfToTab.png ./
cp ~/git/BMMB554/hugo/static/img/mt_tab.png ./
cp ~/git/BMMB554/hugo/static/img/mt_cut.png ./
