- doc: Test outline for Training-Sanger-sequences-CHD8
  job:
    Prim:
      class: File
      path: test-data/Prim.fasta
      filetype: fasta
    AOPEP_and_CHD8_sequences_20220907.zip?download=1:
      class: File
      path: test-data/AOPEP_and_CHD8_sequences_20220907.zip_download=1.zip
      filetype: zip
  outputs: 
    w_blast_output:
      path: test-data/aligned_seqs.fasta
    w_consensus_aligned_sequences:
      path: test-data/blast.tabular

