name: Lint Data Libraries

on:
  pull_request:
    paths:
      - '**/data-library.yaml'

jobs:
  lint-workflows:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Check yaml are valid and can be merged
        run: |
          python bin/mergeyaml.py --nondocker > /dev/null
