name: Lint for Broken Symlinks

on: [pull_request]

jobs:
  lint-broken-symlinks:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Check for broken symlinks
        run: |
          bash bin/check-broken-symlinks.sh
