name: Lint for Broken Symlinks, FAQs

concurrency:
  group: ci-symlinks-${{ github.head_ref }}
  cancel-in-progress: true

on: [pull_request]

jobs:
  lint-broken-symlinks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Check for broken symlinks
        if: always()
        run: |
          bash bin/check-broken-symlinks.sh

      - name: Check for broken snippet links
        if: always()
        run: |
          bash bin/check-snippet-links.sh
