name: Tag Monthly GTN Release

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 4 1 * *'

jobs:
  setup:
    if: github.repository_owner == 'galaxyproject'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: 'x64'

      - name: Release Name
        id: release_name
        run: |
          echo "::set-output name=title::$(LC_ALL=C date '+%Y %B')"
          echo "::set-output name=tag::$(LC_ALL=C date -I)"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.release_name.outputs.tag }}
          commitish: master
          release_name: Release ${{ steps.release_name.outputs.title }}
          body: "Monthly release of the GTN materials"
          draft: false
          prerelease: false
