name: "[Cron] Send Single-cell Galaxy Help Topics to Matrix CoP Room"

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # We'll run this every monday at noon
    - cron:  '0 12 * * 1'
  workflow_dispatch:

jobs:
  runner-job:
    if: github.repository_owner == 'galaxyproject'
    runs-on: ubuntu-latest

    steps:
      # BEGIN Dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y coreutils curl libxml2-utils gawk sed grep jq wget
      # END Dependencies

      - name: Send announcements to single-cell matrix for unanswered posts
        run: |
            wget https://raw.githubusercontent.com/galaxyproject/training-material/main/bin/galaxy-help-news.sh
            HTML_TYPE="bullets" MAX_REPLIES="0" WANTED_TAGS="scrna scrna-seq" ROOM_ID='!TJRLNvfcbWbSRoUNpl:matrix.org' bash ./galaxy-help-news.sh
        env:
            MATRIX_ACCESS_TOKEN: ${{ secrets.matrix_access_token }}
