title: Reflect on your skills as a trainer
contributors:
- bebatut

questions:
- title: Looking at the GOBLET Skill Matrix, on which areas do you need to develop in?
  image: /training-material/topics/teaching/tutorialS/learner_participation_engagement/images/goblet_matrix.png
  answers:
  - Communication
  - Planning & management
  - Trainee engagement
  - Expertise & knowledge
  timeout: 60
  type: poll
- title: Which skills do you need to improve in communication?
  image: /training-material/topics/teaching/tutorialS/learner_participation_engagement/images/goblet_matrix.png
  answers:
  - Verbal communication skills
  - Written communication skills
  - Presentation skills
  timeout: 30
  type: poll
- title: Which skills do you need to improve in planning & management?
  image: /training-material/topics/teaching/tutorialS/learner_participation_engagement/images/goblet_matrix.png
  answers:
  - Session planning
  - Curriculum planning
  - Event management
  timeout: 30
  type: poll
- title: Which skills do you need to improve in trainee engagement?
  image: /training-material/topics/teaching/tutorialS/learner_participation_engagement/images/goblet_matrix.png
  answers:
  - Flexibility in delivery
  - Empathy with trainees
  - Understanding & knowledge of trainees
  timeout: 30
  type: poll
- title: Which skills do you need to improve in expertise & knowledge?
  image: /training-material/topics/teaching/tutorialS/learner_participation_engagement/images/goblet_matrix.png
  answers:
  - Subject area knowledge
  - User application awareness
  - Knowledge of training methodology
  timeout: 30
  type: poll